In [12]:
import numpy as np
features = np.array([[1,2,3], [10,12,23]])
print(np.median(features, axis=0))
loc = np.median(features, axis=0)
scale = np.sum(np.abs(features - loc), axis=0) / features.shape[0]
print(f"loc: {loc} \nscale: {scale}")

[ 5.5  7.  13. ]
loc: [ 5.5  7.  13. ] 
scale: [ 4.5  5.  10. ]


In [14]:
        b = 0
        for element in features:
            b += np.abs(element - loc)
        scale_ = 1./features.shape[0] * b
        print(scale_)

[ 4.5  5.  10. ]


In [15]:
features.shape[0]

2

In [18]:
values = features
res = np.log(1 / (2 * scale)) + (-np.abs(values - loc) / scale)
print(res)

[[-3.19722458 -3.30258509 -3.99573227]
 [-3.19722458 -3.30258509 -3.99573227]]


In [20]:
######
ret = []
for value in values:
    ret_i = []
    for value_i, mu_i, b_i in zip(value, loc, scale_):
        ret_i.append(-np.log(2 * b_i) - np.abs(value_i - mu_i) / b_i)
    ret.append(np.array(ret_i))
print(np.array(ret))

[[-3.19722458 -3.30258509 -3.99573227]
 [-3.19722458 -3.30258509 -3.99573227]]
