In [13]:
import numpy as np

a = np.array([1,2,3]).T
print(np.tile(a, (3, 1)), '\n \n', a)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 
 
 [1 2 3]


In [104]:
from sklearn import datasets
dataset = datasets.load_digits()

# First 100 images will be used for testing. This dataset is not sorted by the labels, so it's ok
# to do the split this way.
# Please be careful when you split your data into train and test in general.
test_border = 5
X_train, y_train = dataset.data[test_border:11], dataset.target[test_border:11]
X_test, y_test = dataset.data[:test_border], dataset.target[:test_border]

print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)
num_test = X_test.shape[0]

Training data shape:  (6, 64)
Training labels shape:  (6,)
Test data shape:  (5, 64)
Test labels shape:  (5,)


In [111]:
        num_test = X_test.shape[0]
        num_train = X_train.shape[0]
        dists_1 = np.zeros((num_test, num_train))
        for i in range(num_test):
            for j in range(num_train):
                #####################################################################
                # TODO:                                                             #
                # Compute the l2 distance between the ith test point and the jth    #
                # training point, and store the result in dists[i, j]. You should   #
                # not use a loop over dimension, nor use np.linalg.norm().          #
                #####################################################################
                # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
                dists_1[i][j] = np.sqrt(np.sum((X_train[j] - X_test[i]) ** 2))
                # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
print(dists_1)

[[43.9089968  48.55924217 56.         44.39594576 40.80441153 23.70653918]
 [47.12748667 40.28647416 50.96076922 48.62098312 52.82045058 54.65345369]
 [55.4436651  45.65084884 49.33558553 42.60281681 54.83611948 46.79743583]
 [33.66006536 47.2546294  56.82429058 42.44997055 45.16635916 52.22068556]
 [54.14794548 36.95943723 59.48108943 52.50714237 55.05451843 44.11349   ]]


In [118]:
        num_test = X_test.shape[0]
        num_train = X_train.shape[0]
        dists_2 = np.zeros((num_test, num_train))
        for i in range(num_test):
            #######################################################################
            # TODO:                                                               #
            # Compute the l2 distance between the ith test point and all training #
            # points, and store the result in dists[i, :].                        #
            # Do not use np.linalg.norm().                                        #
            #######################################################################
            # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
            
            ###A = X_train - X_test[i] 
            ###dists_2[i] = np.sqrt(np.diag(A @ A.T))  
            A = X_train - X_test[i]
            print(f"-------{A.shape}-------")
            print(f"----{np.sum(A * A, axis=1).shape}------------")
            dists[i] = np.sqrt(np.sum(A * A, axis=0))
print(dists_2)

-------(6, 64)-------
----(6,)------------


ValueError: could not broadcast input array from shape (64,) into shape (6,)

In [114]:
dists_no = np.zeros((num_test, num_train))
X_2 = np.tile(np.sum(X_test * X_test, axis=1).reshape((num_test,1)), (1, num_train))
A_2 = np.tile(np.sum(X_train * X_train, axis=1), (num_test, 1))
X_A = 2 * (X_test @ X_train.T)
dists_no = np.sqrt(X_2 - X_A + A_2)
print(dists_no)

[[43.9089968  48.55924217 56.         44.39594576 40.80441153 23.70653918]
 [47.12748667 40.28647416 50.96076922 48.62098312 52.82045058 54.65345369]
 [55.4436651  45.65084884 49.33558553 42.60281681 54.83611948 46.79743583]
 [33.66006536 47.2546294  56.82429058 42.44997055 45.16635916 52.22068556]
 [54.14794548 36.95943723 59.48108943 52.50714237 55.05451843 44.11349   ]]


In [97]:
dists_1, dists_2, dists_no

(array([[ 3.36749165,  6.7037303 , 11.84651848,  6.33561362],
        [ 0.        ,  3.46410162,  8.66025404,  3.        ],
        [ 3.46410162,  0.        ,  5.19615242,  1.        ]]),
 array([[ 3.36749165,  6.7037303 , 11.84651848,  6.33561362],
        [ 0.        ,  3.46410162,  8.66025404,  3.        ],
        [ 3.46410162,  0.        ,  5.19615242,  1.        ]]),
 array([[ 3.36749165,  6.7037303 , 11.84651848,  6.33561362],
        [ 0.        ,  3.46410162,  8.66025404,  3.        ],
        [ 3.46410162,  0.        ,  5.19615242,  1.        ]]))